### ISSUE TITLE
is the project still working and can be implemented???

### ISSUE THREAD

**Issue by dearemraan** [Daltonic/genesis#2]
after submit button application is not running and in blockchain no Ethereum object its showing error   can u please help me out

**Comment by shokushwaha** [comment]
> after submit button application is not running and in blockchain no Ethereum object its showing error can u please help me out
did you find out the solution ? I'm getting the same error

**Comment by codingwithsaleem** [comment]
bro kindly update the project  


Uncaught (in promise) Error: No ethereum object.
    at Zs (blockchain.jsx:220:9)
    at blockchain.jsx:116:5
    at c (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.throw (regeneratorRuntime.js:69:21)
    at Fe (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
genesis-45443.web.app/:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/fonts/CircularXXWeb-Book.woff2

**Comment by codingwithsaleem** [comment]
error hardhat@2.12.2: The engine "node" is incompatible with this module. Expected version "^14.0.0 || ^16.0.0 || ^18.0.0". Got "20.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by SamsonRoi** [comment]
> after submit button application is not running and in blockchain no Ethereum object its showing error can u please help me out

Same issue here
